# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DataMessage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DataMessage.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11\x44\x61taMessage.proto\"\x83\x01\n\x0b\x44\x61taMessage\x12\x19\n\x0cMessage_Name\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x17\n\nMessage_ID\x18\x02 \x01(\tH\x01\x88\x01\x01\x12 \n\x0cMessage_Data\x18\x03 \x03(\x0b\x32\n.DataFrameB\x0f\n\r_Message_NameB\r\n\x0b_Message_ID\".\n\tDataFrame\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x01\x12\x13\n\x0bstring_data\x18\x02 \x03(\tb\x06proto3'
)




_DATAMESSAGE = _descriptor.Descriptor(
  name='DataMessage',
  full_name='DataMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Message_Name', full_name='DataMessage.Message_Name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Message_ID', full_name='DataMessage.Message_ID', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Message_Data', full_name='DataMessage.Message_Data', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_Message_Name', full_name='DataMessage._Message_Name',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_Message_ID', full_name='DataMessage._Message_ID',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=22,
  serialized_end=153,
)


_DATAFRAME = _descriptor.Descriptor(
  name='DataFrame',
  full_name='DataFrame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='DataFrame.data', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='string_data', full_name='DataFrame.string_data', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=155,
  serialized_end=201,
)

_DATAMESSAGE.fields_by_name['Message_Data'].message_type = _DATAFRAME
_DATAMESSAGE.oneofs_by_name['_Message_Name'].fields.append(
  _DATAMESSAGE.fields_by_name['Message_Name'])
_DATAMESSAGE.fields_by_name['Message_Name'].containing_oneof = _DATAMESSAGE.oneofs_by_name['_Message_Name']
_DATAMESSAGE.oneofs_by_name['_Message_ID'].fields.append(
  _DATAMESSAGE.fields_by_name['Message_ID'])
_DATAMESSAGE.fields_by_name['Message_ID'].containing_oneof = _DATAMESSAGE.oneofs_by_name['_Message_ID']
DESCRIPTOR.message_types_by_name['DataMessage'] = _DATAMESSAGE
DESCRIPTOR.message_types_by_name['DataFrame'] = _DATAFRAME
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DataMessage = _reflection.GeneratedProtocolMessageType('DataMessage', (_message.Message,), {
  'DESCRIPTOR' : _DATAMESSAGE,
  '__module__' : 'DataMessage_pb2'
  # @@protoc_insertion_point(class_scope:DataMessage)
  })
_sym_db.RegisterMessage(DataMessage)

DataFrame = _reflection.GeneratedProtocolMessageType('DataFrame', (_message.Message,), {
  'DESCRIPTOR' : _DATAFRAME,
  '__module__' : 'DataMessage_pb2'
  # @@protoc_insertion_point(class_scope:DataFrame)
  })
_sym_db.RegisterMessage(DataFrame)


# @@protoc_insertion_point(module_scope)
